plugin_c_args = ['-DHAVE_CONFIG_H']

cdata = configuration_data()
cdata.set_quoted('PACKAGE_VERSION', gst_version)
cdata.set_quoted('PACKAGE', 'gst-template-plugin')
cdata.set_quoted('GST_LICENSE', 'LGPL')
cdata.set_quoted('GST_API_VERSION', api_version)
cdata.set_quoted('GST_PACKAGE_NAME', 'GStreamer template Plug-ins')
cdata.set_quoted('GST_PACKAGE_ORIGIN', 'https://gstreamer.freedesktop.org')
configure_file(output : 'config.h', configuration : cdata)

gstaudio_dep = dependency('gstreamer-audio-1.0',
    fallback: ['gst-plugins-base', 'audio_dep'])

# ROS2 dependencies
ros2_dep = dependency('rcl', required: true)
ros2c_dep = dependency('rclc', required: true)
ros2cpp_dep = dependency('rclcpp', required: true)
std_msgs_dep = dependency('std_msgs', required: true)
sensor_msgs_dep = dependency('sensor_msgs', required: true)
opencv_dep = dependency('opencv4', required: true)

# Plugin 1
plugin_sources = [
  'src/gstplugin.c'
  ]

gstpluginexample = library('gstplugin',
  plugin_sources,
  c_args: plugin_c_args,
  dependencies : [gst_dep],
  install : true,
  install_dir : plugins_install_dir,
)

# Plugin 2 (audio filter example)
audiofilter_sources = [
  'src/gstaudiofilter.c',
  ]

gstaudiofilterexample = library('gstaudiofilterexample',
  audiofilter_sources,
  c_args: plugin_c_args,
  dependencies : [gst_dep, gstaudio_dep],
  install : true,
  install_dir : plugins_install_dir,
)

# The myfilter Plugin
 gstmyfilter_sources = [
  'src/gstmyfilter.cpp',
  ]

gstmyfilterexample = library('gstmyfilter',
  gstmyfilter_sources,
  c_args: plugin_c_args,
  include_directories: include_directories('.'), 
  dependencies : [gst_dep, gstbase_dep, ros2_dep, ros2cpp_dep, std_msgs_dep],
  install : true,
  install_dir : plugins_install_dir,
)


gst_include = include_directories(gst_dep.get_pkgconfig_variable('includedir'))
gstbase_include = include_directories(gstbase_dep.get_pkgconfig_variable('includedir'))

# The mysrc Plugin
 gstmysrc_sources = [
  'src/gstmysrc.cpp',
  ]

gstmyfilterexample = library('gstmysrc',
  gstmysrc_sources,
  c_args: plugin_c_args,
  include_directories: [include_directories('.'), gst_include, gstbase_include],
  dependencies : [gst_dep, gstbase_dep, ros2_dep, ros2cpp_dep, std_msgs_dep, sensor_msgs_dep, opencv_dep],
  install : true,
  install_dir : plugins_install_dir,
)
